apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev-project
  namespace: argocd

spec:
  description: Development GitOps project

  sourceRepos:
    - https://github.com/tanmaykexe/helm-gitops-demo.git

  destinations:
    - namespace: nginx-dev
      server: https://kubernetes.default.svc

  roles:
    - name: dev-viewer
      description: Read-only access to dev applications
      policies:
        - p, proj:dev-project:dev-viewer, applications, get, dev-project/*, allow
