replicaCount: 2

podEnvironment:
  enabled: true
  value: "development"

image:
  repository: nginx
  tag: "1.27"

service:
  type: ClusterIP
  port: 80

dbCredentials:
  username: "devuser"
  password: "devpassword"
