replicaCount: 1

podEnvironment:
  enabled: true
  value: "development"

image:
  repository: nginx
  tag: "1.27"
  pullPolicy: IfNotPresent

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}

podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

httpRoute:
  enabled: false
  annotations: {}
  parentRefs: []
  hostnames: []
  rules: []

config:
  appName: "my-nginx"
  appMode: "development"
  logLevel: "info"

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: http

readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}

redis:
  enabled: true
  architecture: standalone

  image:
    registry: docker.io
    repository: bitnamilegacy/redis
    tag: "7.4.2-debian-12-r0"
    pullPolicy: IfNotPresent

  auth:
    enabled: true
    password: "redispassword"
